name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install libextractor
      run: |
        apt-get update -y -qq
        apt-get install -y -qq libextractor libextractor-plugins-all
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
