name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install libextractor
      run: |
        sudo apt update && \
        sudo apt install -yq libextractor libextractor-plugins-all
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
