name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - uses: ryankurte/action-apt@v0.1
      with: 
        packages: libextractor libextractor-plugins-all
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
